version: '2'
networks:
  web:
    name: "web"
    External: true
    
services:
  nginx:
    image: nginx
    restart: always
    expose:
      - 80
    volumes:
      - ${df}/wedding:/usr/share/nginx/html
    environment:
      - NGINX_HOST=eskuvo.forrai.online
      - NGINX_PORT=80
    labels:
      - "traefik.backend=eskuvo"
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:eskuvo.forrai.online"
      - "traefik.port=80"
    networks:
      - web
#    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
